### ISSUE TITLE
关于Simple Dataset的像素级标签

### ISSUE THREAD

**Issue by chenmy10** [LovingThresh/RepairerGAN#1]
您好，我在Simple Dataset的论文中只找到了图像以及图像级的标签，请问在哪能够找到该数据集的像素级标签，能否与我分享？非常感谢！

**Comment by LovingThresh** [comment]
I've been on vacation recently, so I don't have access to the server I use for work. I'm going to try to deal with it in the next few days, exposing the data of simple data, and you can also try other datasets.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月21日 16:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [LovingThresh/RepairerGAN] 关于Simple Dataset的像素级标签 (Issue #1) |

您好，我在Simple Dataset的论文中只找到了图像以及图像级的标签，请问在哪能够找到该数据集的像素级标签，能否与我分享？非常感谢！

**Comment by chenmy10** [comment]
> I've been on vacation recently, so I don't have access to the server I use for work. I'm going to try to deal with it in the next few days, exposing the data of simple data, and you can also try other datasets.
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年06月21日 16:11 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [LovingThresh/RepairerGAN] 关于Simple Dataset的像素级标签 (Issue #1) | 您好，我在Simple Dataset的论文中只找到了图像以及图像级的标签，请问在哪能够找到该数据集的像素级标签，能否与我分享？非常感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you! Have a good time~

**Comment by LovingThresh** [comment]
### Experimental Data Overview
([Crack Segmentation Dataset for RepairerGAN](https://drive.google.com/file/d/1wRqrDjBr7owvcbByTB2r1YLyc9fm1bjo/view?usp=drive_link))
The training process encompasses three distinct datasets, each designed to evaluate performance across varying levels of complexity:

- **Simple**:  crack
- **Medium Difficulty** : bridge 
- **Challenging**:  MCFF crack

**Note:** Owing to constraints on the paper's length, the publication focuses exclusively on the results and in-depth analyses of the **Simple** and **Challenging** datasets. Consequently, the **Medium Difficulty** content, exemplified by bridge crack detection, is not expansively discussed within the paper.

**Comment by chenmy10** [comment]
> ### Experimental Data Overview
> ([Crack Segmentation Dataset for RepairerGAN](https://drive.google.com/file/d/1wRqrDjBr7owvcbByTB2r1YLyc9fm1bjo/view?usp=drive_link)) The training process encompasses three distinct datasets, each designed to evaluate performance across varying levels of complexity:
> 
> * **Simple**:  crack
> * **Medium Difficulty** : bridge
> * **Challenging**:  MCFF crack
> 
> **Note:** Owing to constraints on the paper's length, the publication focuses exclusively on the results and in-depth analyses of the **Simple** and **Challenging** datasets. Consequently, the **Medium Difficulty** content, exemplified by bridge crack detection, is not expansively discussed within the paper.

Hi! It seems that I don't have the necessary permissions to view the file you shared. Could you please grant me access to it?

**Comment by LovingThresh** [comment]
sorry，I will set it public！https://drive.google.com/file/d/1wRqrDjBr7owvcbByTB2r1YLyc9fm1bjo/view?usp=sharing



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月29日 18:44 |
| 收件人 | ***@***.***> |
| 抄送至 | LIU ***@***.***>、State ***@***.***> |
| 主题 | Re: [LovingThresh/RepairerGAN] 关于Simple Dataset的像素级标签 (Issue #1) |

Experimental Data Overview

(Crack Segmentation Dataset for RepairerGAN) The training process encompasses three distinct datasets, each designed to evaluate performance across varying levels of complexity:

Simple: crack
Medium Difficulty : bridge
Challenging: MCFF crack

Note: Owing to constraints on the paper's length, the publication focuses exclusively on the results and in-depth analyses of the Simple and Challenging datasets. Consequently, the Medium Difficulty content, exemplified by bridge crack detection, is not expansively discussed within the paper.

Hi! It seems that I don't have the necessary permissions to view the file you shared. Could you please grant me access to it?
